name: "Mutation tests"
on: [ push, pull_request ]

jobs:
    run:
        name: "Mutation tests"
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ ubuntu-latest ]
                php: [ '7.4' ]

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "pcov"
                    php-version: "${{ matrix.php }}"
                    ini-values: memory_limit=-1
                    tools: composer:v2, cs2pr

            -   name: "Cache dependencies"
                uses: "actions/cache@v2"
                with:
                    path: |
                        ~/.composer/cache
                        vendor
                    key: "php-${{ matrix.php }}"
                    restore-keys: "php-${{ matrix.php }}"

            -   name: "Install locked dependencies"
                run: "composer install --no-interaction --no-progress"

            -   name: "Infection"
                run: "./vendor/bin/infection"
                env:
                    INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
                    STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
